pub mod cache;
pub mod checks;
pub mod dashboard;
pub mod compile;
pub mod element;
pub mod figure;
pub mod math;
pub mod symbol;
pub mod config;
pub mod davinci;
pub mod depends;
pub mod diagnostic;
pub mod draft;
pub mod fix;
pub mod layout;
pub mod runner;
pub mod spec_gen;
pub mod slide;
pub mod tree;

pub use config::GlintConfig;
pub use diagnostic::{Diagnostic, RichContext, Severity};
pub use fix::{Confidence, Edit, Fix, FixOptions, FixPlan, FixResult};
pub use runner::Runner;
