use anyhow::Result;
use clap::{Parser, Subcommand};
use colored::Colorize;
use anyhow::Context;
use glint_lib::draft::build_draft_plan;
use glint_lib::fix::{serialize_json, serialize_rich, FixOptions};
use glint_lib::{Confidence, Diagnostic, FixPlan, GlintConfig, Runner, Severity};
use std::path::PathBuf;
use std::process;

#[derive(Parser)]
#[command(
    name = "glint",
    version,
    about = "A fast, schema-driven markdown and ASCII art linter with AI-assisted fix pipeline",
    long_about = None,
)]
struct Cli {
    #[command(subcommand)]
    command: Option<Command>,

    /// Files or directories to lint (default: current directory)
    paths: Vec<PathBuf>,

    /// Schema config file (default: glint.toml in target directory)
    #[arg(short, long, global = true)]
    config: Option<PathBuf>,

    /// Output format: text (default) | json | rich | github
    #[arg(short = 'f', long, default_value = "text", global = true)]
    format: String,

    /// Show only errors (suppress warnings)
    #[arg(short = 'e', long, global = true)]
    errors_only: bool,

    /// Exit with code 0 even if issues found
    #[arg(long, global = true)]
    no_fail: bool,

    /// Write output to file instead of stdout
    #[arg(short = 'o', long, global = true)]
    output: Option<PathBuf>,
}

#[derive(Subcommand)]
enum Command {
    /// Lint files and report diagnostics (default)
    Check {
        paths: Vec<PathBuf>,
    },
    /// Apply a fix plan generated by AI
    Fix {
        /// Fix plan JSON file
        #[arg(long, required = true)]
        plan: PathBuf,
        /// Show diff without writing any files
        #[arg(long)]
        dry_run: bool,
        /// Only apply fixes at or above this confidence: high | medium | low
        #[arg(long, default_value = "high")]
        min_confidence: String,
        /// Skip re-running check after applying fixes
        #[arg(long)]
        no_verify: bool,
        /// Skip signal-loss check (allow fixes that remove non-whitespace content)
        /// Use only when you've confirmed the removed content is preserved elsewhere
        #[arg(long)]
        no_signal_check: bool,
    },
    /// Generate a pre-populated draft fix plan — AI fills in decisions inline
    Draft {
        paths: Vec<PathBuf>,
        /// Output file for the draft plan (default: draft-plan.json)
        #[arg(short = 'o', long, default_value = "draft-plan.json")]
        output: PathBuf,
    },
    /// Print the effective config for a path
    Config,
    /// Write a glint.toml to the current directory
    Init,
    /// Summary statistics (error/warning counts by directory and code)
    Stats {
        paths: Vec<PathBuf>,
        /// Break down by directory
        #[arg(long)]
        by_directory: bool,
        /// Break down by error code
        #[arg(long)]
        by_code: bool,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command.as_ref() {
        Some(Command::Draft { .. }) => {}  // handled below
        _ => {}
    }
    match cli.command {
        Some(Command::Fix { plan, dry_run, min_confidence, no_verify, no_signal_check }) => {
            return cmd_fix(plan, dry_run, min_confidence, no_verify, no_signal_check, &cli.config);
        }
        Some(Command::Draft { paths, output }) => {
            let paths = if paths.is_empty() { vec![std::env::current_dir()?] } else { paths };
            return cmd_draft(paths, output, &cli.config);
        }
        Some(Command::Init) => {
            return cmd_init();
        }
        Some(Command::Config) => {
            println!("(use glint.toml in your project directory — see `glint init`)");
            return Ok(());
        }
        Some(Command::Stats { paths, by_directory, by_code }) => {
            let paths = if paths.is_empty() { vec![std::env::current_dir()?] } else { paths };
            return cmd_stats(paths, by_directory, by_code, &cli.config);
        }
        _ => {}
    }

    // Default: check
    let paths: Vec<PathBuf> = match &cli.command {
        Some(Command::Check { paths }) if !paths.is_empty() => paths.clone(),
        _ if !cli.paths.is_empty() => cli.paths.clone(),
        _ => vec![std::env::current_dir()?],
    };

    cmd_check(paths, &cli)
}

// ─────────────────────────────────────────────────────────
// check
// ─────────────────────────────────────────────────────────

fn cmd_check(paths: Vec<PathBuf>, cli: &Cli) -> Result<()> {
    let mut all_diags: Vec<Diagnostic> = Vec::new();
    let mut files_checked = 0usize;

    for path in &paths {
        let cfg = load_config(path, &cli.config);
        let dir = if path.is_dir() { path.clone() } else { path.parent().unwrap_or(path).to_path_buf() };
        let runner = Runner::new(&dir, cfg)?;

        if path.is_file() {
            files_checked += 1;
            all_diags.extend(runner.lint_file(path));
        } else {
            files_checked += count_files(path);
            all_diags.extend(runner.run());
        }
    }

    if cli.errors_only {
        all_diags.retain(|d| d.severity == Severity::Error);
    }

    all_diags.sort_by(|a, b| {
        a.file.cmp(&b.file)
            .then(a.span.line.cmp(&b.span.line))
            .then(a.span.col.cmp(&b.span.col))
    });

    let error_count = all_diags.iter().filter(|d| d.severity == Severity::Error).count();
    let warn_count = all_diags.iter().filter(|d| d.severity == Severity::Warning).count();

    let out = format_output(&all_diags, &cli.format)?;

    if let Some(ref out_path) = cli.output {
        std::fs::write(out_path, &out)?;
        eprintln!("Output written to {}", out_path.display());
    } else {
        print!("{}", out);
    }

    if !all_diags.is_empty() && cli.format == "text" {
        eprintln!();
    }

    let status = if error_count > 0 { "FAIL".red().bold() } else { "OK".green().bold() };
    eprintln!(
        "{} — {} files checked, {} error{}, {} warning{}",
        status, files_checked,
        error_count, if error_count == 1 { "" } else { "s" },
        warn_count,  if warn_count == 1  { "" } else { "s" },
    );

    if !cli.no_fail && error_count > 0 {
        process::exit(1);
    }
    Ok(())
}

fn format_output(diags: &[Diagnostic], format: &str) -> Result<String> {
    match format {
        "json" => Ok(serialize_json(diags)?),
        "rich" => Ok(serialize_rich(diags)?),
        "github" => {
            let mut out = String::new();
            for d in diags {
                let level = match d.severity {
                    Severity::Error => "error",
                    Severity::Warning => "warning",
                    Severity::Info => "notice",
                };
                out.push_str(&format!(
                    "::{} file={},line={},col={}::[{}] {}\n",
                    level, d.file.display(), d.span.line, d.span.col, d.code, d.message
                ));
            }
            Ok(out)
        }
        _ => {
            // text (default)
            let mut out = String::new();
            for d in diags {
                let sev = match d.severity {
                    Severity::Error => "error".red().bold().to_string(),
                    Severity::Warning => "warning".yellow().bold().to_string(),
                    Severity::Info => "info".blue().to_string(),
                };
                out.push_str(&format!(
                    "{}:{}: {} [{}]: {}\n",
                    d.file.display().to_string().cyan(),
                    d.span.to_string().white(),
                    sev,
                    d.code.dimmed(),
                    d.message
                ));
                if let Some(ref note) = d.note {
                    out.push_str(&format!("  {} {}\n", "note:".dimmed(), note));
                }
            }
            Ok(out)
        }
    }
}

// ─────────────────────────────────────────────────────────
// fix
// ─────────────────────────────────────────────────────────

fn cmd_fix(
    plan_path: PathBuf,
    dry_run: bool,
    min_confidence_str: String,
    no_verify: bool,
    no_signal_check: bool,
    config_override: &Option<PathBuf>,
) -> Result<()> {
    let min_confidence = match min_confidence_str.as_str() {
        "high" => Confidence::High,
        "medium" => Confidence::Medium,
        "low" => Confidence::Low,
        other => {
            eprintln!("glint: unknown confidence level {:?} — use high, medium, or low", other);
            process::exit(2);
        }
    };

    // Accept both FixPlan and DraftPlan (draft → fix via to_fix_plan())
    let plan = load_plan(&plan_path)?;
    let root = std::env::current_dir()?;

    eprintln!(
        "{} {} fixes from {} (min confidence: {}, dry-run: {})",
        if dry_run { "Previewing" } else { "Applying" },
        plan.fixes.len(),
        plan_path.display(),
        min_confidence,
        dry_run,
    );

    let opts = FixOptions { dry_run, min_confidence, check_signal: !no_signal_check };
    let result = plan.apply(&opts, &root)?;

    eprintln!();
    for skip in &result.skipped {
        eprintln!("{} [{}] {}", "SKIP".yellow(), skip.id, skip.reason);
    }

    eprintln!();
    if dry_run {
        eprintln!("{} — {} fixes previewed, {} skipped (no files written)",
            "DRY RUN".cyan().bold(), result.applied.len(), result.skipped.len());
    } else {
        eprintln!(
            "{} — {} fixes applied to {} files, {} skipped",
            "DONE".green().bold(), result.applied.len(), result.files_modified, result.skipped.len()
        );

        // Re-run check unless suppressed
        if !no_verify && result.files_modified > 0 {
            eprintln!("\n{} verifying fixes…", "→".cyan());
            let args = vec![std::env::current_dir()?.to_string_lossy().to_string()];
            let verify_cfg = GlintConfig::load_or_default(&root);
            let runner = Runner::new(&root, verify_cfg)?;
            let diags = runner.run();
            let errors = diags.iter().filter(|d| d.severity == Severity::Error).count();
            if errors == 0 {
                eprintln!("{} zero errors remaining", "✓".green());
            } else {
                eprintln!(
                    "{} {} error{} remain after fix — review manually",
                    "!".yellow(), errors, if errors == 1 { "" } else { "s" }
                );
                let _ = args; // suppress unused warning
                process::exit(1);
            }
        }
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// stats
// ─────────────────────────────────────────────────────────

fn cmd_stats(
    paths: Vec<PathBuf>,
    by_directory: bool,
    by_code: bool,
    _config_override: &Option<PathBuf>,
) -> Result<()> {
    let mut all_diags: Vec<Diagnostic> = Vec::new();
    let mut files_checked = 0usize;

    for path in &paths {
        let cfg = load_config(&path, &None);
        let dir = if path.is_dir() { path.clone() } else { path.parent().unwrap_or(&path).to_path_buf() };
        let runner = Runner::new(&dir, cfg)?;
        if path.is_file() {
            files_checked += 1;
            all_diags.extend(runner.lint_file(path));
        } else {
            files_checked += count_files(path);
            all_diags.extend(runner.run());
        }
    }

    let errors = all_diags.iter().filter(|d| d.severity == Severity::Error).count();
    let warnings = all_diags.iter().filter(|d| d.severity == Severity::Warning).count();

    println!("files:    {}", files_checked);
    println!("errors:   {}", errors);
    println!("warnings: {}", warnings);

    if by_code {
        println!("\nBy error code:");
        let mut by_code_map: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
        for d in &all_diags {
            *by_code_map.entry(d.code).or_default() += 1;
        }
        for (code, count) in &by_code_map {
            println!("  {:30} {}", code, count);
        }
    }

    if by_directory {
        println!("\nBy directory:");
        let mut by_dir: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
        for d in &all_diags {
            let dir = d.file.parent()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| ".".to_string());
            *by_dir.entry(dir).or_default() += 1;
        }
        for (dir, count) in &by_dir {
            println!("  {:50} {}", dir, count);
        }
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────

fn cmd_draft(paths: Vec<PathBuf>, output: PathBuf, config_override: &Option<PathBuf>) -> Result<()> {
    // Collect all diagnostics (same as check)
    let mut all_diags: Vec<Diagnostic> = Vec::new();
    let root = paths.first().map(|p| if p.is_dir() { p.clone() } else { p.parent().unwrap_or(p).to_path_buf() })
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    for path in &paths {
        let cfg = load_config(path, config_override);
        let dir = if path.is_dir() { path.clone() } else { path.parent().unwrap_or(path).to_path_buf() };
        let runner = Runner::new(&dir, cfg)?;
        if path.is_file() {
            all_diags.extend(runner.lint_file(path));
        } else {
            all_diags.extend(runner.run());
        }
    }

    let error_count = all_diags.iter().filter(|d| d.severity == Severity::Error).count();
    let warn_count = all_diags.iter().filter(|d| d.severity == Severity::Warning).count();

    // Build the draft plan
    let draft = build_draft_plan(&all_diags, &root)?;

    let json = serde_json::to_string_pretty(&draft)?;
    std::fs::write(&output, &json)?;

    eprintln!(
        "{} — {} errors, {} warnings across {} groups ({} auto-fixable, {} need review)",
        "draft".cyan().bold(),
        error_count, warn_count,
        draft.summary.total_groups,
        draft.summary.auto_fixable,
        draft.summary.needs_review,
    );
    eprintln!("Draft plan written to {}", output.display().to_string().cyan());
    eprintln!();
    eprintln!("Next steps:");
    eprintln!("  1. Open {} — AI fills in `decision` and `new_string` for non-auto groups", output.display());
    eprintln!("  2. glint fix --plan {} --dry-run", output.display());
    eprintln!("  3. glint fix --plan {}", output.display());

    Ok(())
}

/// Load a plan file — accepts both FixPlan and DraftPlan formats.
/// DraftPlan is automatically converted to FixPlan via to_fix_plan().
fn load_plan(path: &std::path::Path) -> anyhow::Result<FixPlan> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("reading plan file: {}", path.display()))?;

    // Try FixPlan first (has "schema_version" + "fixes" array)
    if let Ok(plan) = serde_json::from_str::<FixPlan>(&content) {
        return Ok(plan);
    }

    // Try DraftPlan (has "schema_version" + "groups" array)
    if let Ok(draft) = serde_json::from_str::<glint_lib::draft::DraftPlan>(&content) {
        eprintln!("{} converting draft plan to fix plan (auto+annotated groups only)",
            "info:".cyan());
        return Ok(draft.to_fix_plan());
    }

    anyhow::bail!("cannot parse {} as FixPlan or DraftPlan", path.display())
}

fn load_config(path: &std::path::Path, override_path: &Option<PathBuf>) -> GlintConfig {
    if let Some(ref cfg_path) = override_path {
        match GlintConfig::load(cfg_path) {
            Ok(cfg) => return cfg,
            Err(e) => eprintln!("glint: warning: {}", e),
        }
    }
    let dir = if path.is_dir() { path.to_path_buf() } else { path.parent().unwrap_or(path).to_path_buf() };
    GlintConfig::load_or_default(&dir)
}

fn cmd_init() -> Result<()> {
    let path = std::path::Path::new("glint.toml");
    if path.exists() {
        eprintln!("{} glint.toml already exists", "warning:".yellow());
        return Ok(());
    }
    let content = include_str!("../schemas/default.toml");
    std::fs::write(path, content)?;
    println!("{} glint.toml created", "OK".green().bold());
    Ok(())
}

fn count_files(dir: &std::path::Path) -> usize {
    walkdir::WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
        .count()
}
