use anyhow::Result;
use clap::{Parser, Subcommand};
use colored::Colorize;
use anyhow::Context;
use proof_lib::davinci::check_daVinci;
use proof_lib::draft::build_draft_plan;
use proof_lib::fix::{serialize_json, serialize_rich, FixOptions};
use proof_lib::compile::{compile_file, derive_output_path, ViolationSeverity};
use proof_lib::spec_gen;
use proof_lib::layout::{self, Align, Direction, LayoutConfig, extract_content_lines};
use proof_lib::{Confidence, Diagnostic, FixPlan, GlintConfig, Runner, Severity};
use std::path::PathBuf;
use std::process;

#[derive(Parser)]
#[command(
    name = "proof",
    version,
    about = "A fast, schema-driven markdown and ASCII art linter with AI-assisted fix pipeline",
    long_about = None,
)]
struct Cli {
    #[command(subcommand)]
    command: Option<Command>,

    /// Files or directories to lint (default: current directory)
    paths: Vec<PathBuf>,

    /// Schema config file (default: proof.toml in target directory)
    #[arg(short, long, global = true)]
    config: Option<PathBuf>,

    /// Output format: text (default) | json | rich | github
    #[arg(short = 'f', long, default_value = "text", global = true)]
    format: String,

    /// Show only errors (suppress warnings)
    #[arg(short = 'e', long, global = true)]
    errors_only: bool,

    /// Exit with code 0 even if issues found
    #[arg(long, global = true)]
    no_fail: bool,

    /// Write output to file instead of stdout
    #[arg(short = 'o', long, global = true)]
    output: Option<PathBuf>,
}

#[derive(Subcommand)]
enum Command {
    /// Lint files and report diagnostics (default)
    Check {
        paths: Vec<PathBuf>,
        /// Also validate all pinned DaVinci figures against their invariants
        #[arg(long = "daVinci")]
        da_vinci: bool,
    },
    /// Apply a fix plan generated by AI
    Fix {
        /// Fix plan JSON file
        #[arg(long, required = true)]
        plan: PathBuf,
        /// Show diff without writing any files
        #[arg(long)]
        dry_run: bool,
        /// Only apply fixes at or above this confidence: high | medium | low
        #[arg(long, default_value = "high")]
        min_confidence: String,
        /// Skip re-running check after applying fixes
        #[arg(long)]
        no_verify: bool,
        /// Skip signal-loss check (allow fixes that remove non-whitespace content)
        /// Use only when you've confirmed the removed content is preserved elsewhere
        #[arg(long)]
        no_signal_check: bool,
    },
    /// Generate a pre-populated draft fix plan — AI fills in decisions inline
    Draft {
        paths: Vec<PathBuf>,
        /// Output file for the draft plan (default: draft-plan.json)
        #[arg(short = 'o', long, default_value = "draft-plan.json")]
        output: PathBuf,
    },
    /// Pin a figure as a DaVinci — registers it in proof.toml with invariants
    Pin {
        /// The md:// URI to pin
        uri: String,
        /// Stable identifier for this pin
        #[arg(long, required = true)]
        id: String,
        /// Human description
        #[arg(long, default_value = "")]
        description: String,
        /// Template name for base invariants
        #[arg(long)]
        template: Option<String>,
        /// Protection tier: warn | error | lock
        #[arg(long, default_value = "warn")]
        protection: String,
        /// Root directory (default: current directory)
        #[arg(long)]
        root: Option<PathBuf>,
        /// Config file to update (default: proof.toml in current directory)
        #[arg(long)]
        config_file: Option<PathBuf>,
    },
    /// List all pinned DaVinci figures
    PinList,
    /// Resolve an md:// URI — print the element content, label, and line range
    Resolve {
        /// The md:// URI to resolve
        uri: String,
        /// Root directory (default: current directory, or where proof.toml lives)
        #[arg(short, long)]
        root: Option<PathBuf>,
        /// Output format: text (default) | json
        #[arg(short = 'f', long, default_value = "text")]
        format: String,
    },
    /// Print the effective config for a path
    Config,
    /// Write a proof.toml to the current directory
    Init,
    /// Summary statistics (error/warning counts by directory and code)
    Stats {
        paths: Vec<PathBuf>,
        /// Break down by directory
        #[arg(long)]
        by_directory: bool,
        /// Break down by error code
        #[arg(long)]
        by_code: bool,
    },
    /// Compile source documents — resolve proof: directives and write output
    Compile {
        /// Source files or directories (default: current directory)
        paths: Vec<PathBuf>,
        /// Explicit output path (only valid for single-file compile)
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,
        /// Validate without writing any output files
        #[arg(long)]
        check: bool,
        /// Root directory for md:// URI resolution (default: proof.toml location or cwd)
        #[arg(long)]
        root: Option<PathBuf>,
    },
    /// Analyze a figure and generate suggested DaVinci invariants
    SpecGenerate {
        /// The md:// URI of the figure to analyze
        uri: String,
        /// Stable ID for the [[davinci]] entry (default: derived from URI)
        #[arg(long)]
        id: Option<String>,
        /// Protection tier: warn | error | lock (default: error)
        #[arg(long, default_value = "error")]
        protection: String,
        /// Root directory for URI resolution (default: cwd)
        #[arg(long)]
        root: Option<PathBuf>,
        /// Write output to file instead of stdout
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,
    },
    /// Compose N figures side-by-side into a single ASCII art collage
    Layout {
        /// Source figures: md:// URIs or file paths
        sources: Vec<String>,
        /// Spaces between frames (default: 3)
        #[arg(long, default_value = "3")]
        gap: usize,
        /// Vertical alignment: top | center | bottom (default: top)
        #[arg(long, default_value = "top")]
        align: String,
        /// Labels above each frame (one per source, space-separated)
        #[arg(long, num_args = 0..)]
        labels: Vec<String>,
        /// Number of frames per row before wrapping (default: all)
        #[arg(long)]
        cols: Option<usize>,
        /// Max output width in columns (default: 120)
        #[arg(long, default_value = "120")]
        width: usize,
        /// Composition direction: horizontal | vertical (or h | v)
        #[arg(long, default_value = "horizontal")]
        direction: String,
        /// Add a border box around each frame
        #[arg(long)]
        border: bool,
        /// Write output to file (default: stdout)
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,
        /// Root directory for md:// URI resolution (default: current directory)
        #[arg(long)]
        root: Option<PathBuf>,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command.as_ref() {
        Some(Command::Draft { .. }) => {}  // handled below
        _ => {}
    }
    match cli.command {
        Some(Command::Fix { plan, dry_run, min_confidence, no_verify, no_signal_check }) => {
            return cmd_fix(plan, dry_run, min_confidence, no_verify, no_signal_check, &cli.config);
        }
        Some(Command::Draft { paths, output }) => {
            let paths = if paths.is_empty() { vec![std::env::current_dir()?] } else { paths };
            return cmd_draft(paths, output, &cli.config);
        }
        Some(Command::Resolve { uri, root, format }) => {
            return cmd_resolve(uri, root, format);
        }
        Some(Command::Pin { uri, id, description, template, protection, root, config_file }) => {
            return cmd_pin(uri, id, description, template, protection, root, config_file);
        }
        Some(Command::PinList) => {
            return cmd_pin_list(&cli.config);
        }
        Some(Command::Init) => {
            return cmd_init();
        }
        Some(Command::Config) => {
            println!("(use proof.toml in your project directory — see `proof init`)");
            return Ok(());
        }
        Some(Command::Stats { paths, by_directory, by_code }) => {
            let paths = if paths.is_empty() { vec![std::env::current_dir()?] } else { paths };
            return cmd_stats(paths, by_directory, by_code, &cli.config);
        }
        Some(Command::SpecGenerate { uri, id, protection, root, output }) => {
            return cmd_spec_generate(uri, id, protection, root, output);
        }
        Some(Command::Compile { paths, output, check, root }) => {
            let paths = if paths.is_empty() { vec![std::env::current_dir()?] } else { paths };
            return cmd_compile(paths, output, check, root, &cli.config);
        }
        Some(Command::Layout {
            sources, gap, align, labels, cols, width, direction, border, output, root,
        }) => {
            return cmd_layout(
                sources, gap, align, labels, cols, width, direction, border, output, root,
            );
        }
        _ => {}
    }

    // Default: check
    let (paths, da_vinci) = match &cli.command {
        Some(Command::Check { paths, da_vinci }) => (
            if paths.is_empty() { vec![] } else { paths.clone() },
            *da_vinci,
        ),
        _ => (vec![], false),
    };
    let paths = if paths.is_empty() && !cli.paths.is_empty() {
        cli.paths.clone()
    } else if paths.is_empty() {
        vec![std::env::current_dir()?]
    } else {
        paths
    };

    cmd_check(paths, &cli, da_vinci)
}

// ─────────────────────────────────────────────────────────
// check
// ─────────────────────────────────────────────────────────

fn cmd_check(paths: Vec<PathBuf>, cli: &Cli, da_vinci: bool) -> Result<()> {
    let mut all_diags: Vec<Diagnostic> = Vec::new();
    let mut files_checked = 0usize;

    // DaVinci root = the directory containing proof.toml (the proof root)
    // Run once, not per-file, using the config's location as the URI root
    if da_vinci {
        let proof_root = cli.config.as_deref()
            .and_then(|p| std::path::Path::new(p).parent())
            .map(|p| p.to_path_buf())
            .unwrap_or_else(|| paths.first()
                .map(|p| if p.is_dir() { p.clone() } else { p.parent().unwrap_or(p).to_path_buf() })
                .unwrap_or_else(|| std::env::current_dir().unwrap())
            );
        let cfg = load_config(&proof_root, &cli.config);
        if !cfg.davinci.is_empty() {
            let dv_diags = check_daVinci(&cfg, &proof_root);
            if dv_diags.is_empty() {
                eprintln!("{} all {} DaVinci invariants satisfied",
                    "✓".green(), cfg.davinci.len());
            }
            all_diags.extend(dv_diags);
        }
    }

    for path in &paths {
        let cfg = load_config(path, &cli.config);
        let dir = if path.is_dir() { path.clone() } else { path.parent().unwrap_or(path).to_path_buf() };
        let runner = Runner::new(&dir, cfg)?;

        if path.is_file() {
            files_checked += 1;
            all_diags.extend(runner.lint_file(path));
        } else {
            files_checked += count_files(path);
            all_diags.extend(runner.run());
        }
    }

    if cli.errors_only {
        all_diags.retain(|d| d.severity == Severity::Error);
    }

    all_diags.sort_by(|a, b| {
        a.file.cmp(&b.file)
            .then(a.span.line.cmp(&b.span.line))
            .then(a.span.col.cmp(&b.span.col))
    });

    let error_count = all_diags.iter().filter(|d| d.severity == Severity::Error).count();
    let warn_count = all_diags.iter().filter(|d| d.severity == Severity::Warning).count();

    let out = format_output(&all_diags, &cli.format)?;

    if let Some(ref out_path) = cli.output {
        std::fs::write(out_path, &out)?;
        eprintln!("Output written to {}", out_path.display());
    } else {
        print!("{}", out);
    }

    if !all_diags.is_empty() && cli.format == "text" {
        eprintln!();
    }

    let status = if error_count > 0 { "FAIL".red().bold() } else { "OK".green().bold() };
    eprintln!(
        "{} — {} files checked, {} error{}, {} warning{}",
        status, files_checked,
        error_count, if error_count == 1 { "" } else { "s" },
        warn_count,  if warn_count == 1  { "" } else { "s" },
    );

    if !cli.no_fail && error_count > 0 {
        process::exit(1);
    }
    Ok(())
}

fn format_output(diags: &[Diagnostic], format: &str) -> Result<String> {
    match format {
        "json" => Ok(serialize_json(diags)?),
        "rich" => Ok(serialize_rich(diags)?),
        "github" => {
            let mut out = String::new();
            for d in diags {
                let level = match d.severity {
                    Severity::Error => "error",
                    Severity::Warning => "warning",
                    Severity::Info => "notice",
                };
                out.push_str(&format!(
                    "::{} file={},line={},col={}::[{}] {}\n",
                    level, d.file.display(), d.span.line, d.span.col, d.code, d.message
                ));
            }
            Ok(out)
        }
        _ => {
            // text (default)
            let mut out = String::new();
            for d in diags {
                let sev = match d.severity {
                    Severity::Error => "error".red().bold().to_string(),
                    Severity::Warning => "warning".yellow().bold().to_string(),
                    Severity::Info => "info".blue().to_string(),
                };
                out.push_str(&format!(
                    "{}:{}: {} [{}]: {}\n",
                    d.file.display().to_string().cyan(),
                    d.span.to_string().white(),
                    sev,
                    d.code.dimmed(),
                    d.message
                ));
                if let Some(ref note) = d.note {
                    out.push_str(&format!("  {} {}\n", "note:".dimmed(), note));
                }
            }
            Ok(out)
        }
    }
}

// ─────────────────────────────────────────────────────────
// fix
// ─────────────────────────────────────────────────────────

fn cmd_fix(
    plan_path: PathBuf,
    dry_run: bool,
    min_confidence_str: String,
    no_verify: bool,
    no_signal_check: bool,
    config_override: &Option<PathBuf>,
) -> Result<()> {
    let min_confidence = match min_confidence_str.as_str() {
        "high" => Confidence::High,
        "medium" => Confidence::Medium,
        "low" => Confidence::Low,
        other => {
            eprintln!("proof: unknown confidence level {:?} — use high, medium, or low", other);
            process::exit(2);
        }
    };

    // Accept both FixPlan and DraftPlan (draft → fix via to_fix_plan())
    let plan = load_plan(&plan_path)?;
    let root = std::env::current_dir()?;

    eprintln!(
        "{} {} fixes from {} (min confidence: {}, dry-run: {})",
        if dry_run { "Previewing" } else { "Applying" },
        plan.fixes.len(),
        plan_path.display(),
        min_confidence,
        dry_run,
    );

    let opts = FixOptions { dry_run, min_confidence, check_signal: !no_signal_check };
    let result = plan.apply(&opts, &root)?;

    eprintln!();
    for skip in &result.skipped {
        eprintln!("{} [{}] {}", "SKIP".yellow(), skip.id, skip.reason);
    }

    eprintln!();
    if dry_run {
        eprintln!("{} — {} fixes previewed, {} skipped (no files written)",
            "DRY RUN".cyan().bold(), result.applied.len(), result.skipped.len());
    } else {
        eprintln!(
            "{} — {} fixes applied to {} files, {} skipped",
            "DONE".green().bold(), result.applied.len(), result.files_modified, result.skipped.len()
        );

        // Re-run check unless suppressed
        if !no_verify && result.files_modified > 0 {
            eprintln!("\n{} verifying fixes…", "→".cyan());
            let args = vec![std::env::current_dir()?.to_string_lossy().to_string()];
            let verify_cfg = GlintConfig::load_or_default(&root);
            let runner = Runner::new(&root, verify_cfg)?;
            let diags = runner.run();
            let errors = diags.iter().filter(|d| d.severity == Severity::Error).count();
            if errors == 0 {
                eprintln!("{} zero errors remaining", "✓".green());
            } else {
                eprintln!(
                    "{} {} error{} remain after fix — review manually",
                    "!".yellow(), errors, if errors == 1 { "" } else { "s" }
                );
                let _ = args; // suppress unused warning
                process::exit(1);
            }
        }
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// stats
// ─────────────────────────────────────────────────────────

fn cmd_stats(
    paths: Vec<PathBuf>,
    by_directory: bool,
    by_code: bool,
    _config_override: &Option<PathBuf>,
) -> Result<()> {
    let mut all_diags: Vec<Diagnostic> = Vec::new();
    let mut files_checked = 0usize;

    for path in &paths {
        let cfg = load_config(&path, &None);
        let dir = if path.is_dir() { path.clone() } else { path.parent().unwrap_or(&path).to_path_buf() };
        let runner = Runner::new(&dir, cfg)?;
        if path.is_file() {
            files_checked += 1;
            all_diags.extend(runner.lint_file(path));
        } else {
            files_checked += count_files(path);
            all_diags.extend(runner.run());
        }
    }

    let errors = all_diags.iter().filter(|d| d.severity == Severity::Error).count();
    let warnings = all_diags.iter().filter(|d| d.severity == Severity::Warning).count();

    println!("files:    {}", files_checked);
    println!("errors:   {}", errors);
    println!("warnings: {}", warnings);

    if by_code {
        println!("\nBy error code:");
        let mut by_code_map: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
        for d in &all_diags {
            *by_code_map.entry(d.code).or_default() += 1;
        }
        for (code, count) in &by_code_map {
            println!("  {:30} {}", code, count);
        }
    }

    if by_directory {
        println!("\nBy directory:");
        let mut by_dir: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
        for d in &all_diags {
            let dir = d.file.parent()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| ".".to_string());
            *by_dir.entry(dir).or_default() += 1;
        }
        for (dir, count) in &by_dir {
            println!("  {:50} {}", dir, count);
        }
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────
// resolve
// ─────────────────────────────────────────────────────────

fn cmd_pin(
    uri: String,
    id: String,
    description: String,
    template: Option<String>,
    protection: String,
    root: Option<PathBuf>,
    config_file: Option<PathBuf>,
) -> Result<()> {
    let root = root.unwrap_or_else(|| std::env::current_dir().unwrap());
    let config_path = config_file.unwrap_or_else(|| root.join("proof.toml"));

    // Resolve the URI first to verify it works and get metadata
    let parsed = mdpath::parse(&uri)
        .map_err(|e| anyhow::anyhow!("invalid md:// URI: {}", e))?;
    let element = mdpath::resolve(&parsed, &root)
        .map_err(|e| anyhow::anyhow!("cannot resolve URI: {}", e))?;

    // Use the named form of the URI (strings over numbers)
    let stable_uri = element.uri.clone();

    // Build TOML snippet to append
    let desc = if description.is_empty() {
        element.label.as_deref().unwrap_or("").to_string()
    } else {
        description
    };

    let template_line = template
        .as_deref()
        .map(|t| format!("\ntemplate = {:?}", t))
        .unwrap_or_default();

    let toml_snippet = format!(
        "\n[[davinci]]\nid = {:?}\nuri = {:?}\ndescription = {:?}\nprotection = {:?}{}\n",
        id, stable_uri, desc, protection, template_line
    );

    // Append to proof.toml
    let existing = std::fs::read_to_string(&config_path).unwrap_or_default();
    if existing.contains(&format!("id = {:?}", id)) {
        eprintln!("{} DaVinci '{}' already exists in {} — update it manually",
            "warn:".yellow(), id, config_path.display());
        return Ok(());
    }
    std::fs::write(&config_path, format!("{}{}", existing, toml_snippet))?;

    eprintln!("{} Pinned {} as '{}'", "✓".green().bold(), stable_uri.cyan(), id);
    eprintln!("  Kind: {}", element.kind.as_deref().unwrap_or("figure"));
    eprintln!("  Lines: {}–{}", element.line_start, element.line_end);
    if let Some(label) = &element.label {
        eprintln!("  Label: {}", label);
    }
    eprintln!();
    eprintln!("Add invariants to {}", config_path.display());
    eprintln!("Then run: proof check --daVinci .");

    Ok(())
}

fn cmd_pin_list(config_override: &Option<PathBuf>) -> Result<()> {
    let root = std::env::current_dir()?;
    let cfg = load_config(&root, config_override);
    if cfg.davinci.is_empty() {
        println!("No DaVinci entries registered. Use `proof pin md://... --id name` to pin a figure.");
        return Ok(());
    }
    println!("{} DaVinci entries:", cfg.davinci.len());
    for entry in &cfg.davinci {
        let inv_count = entry.invariants.len();
        println!(
            "  {} [{}] {} — {} invariant{}",
            entry.id.cyan().bold(),
            entry.protection,
            entry.uri,
            inv_count,
            if inv_count == 1 { "" } else { "s" }
        );
        if !entry.description.is_empty() {
            println!("    {}", entry.description.dimmed());
        }
    }
    Ok(())
}

fn cmd_resolve(uri: String, root: Option<PathBuf>, format: String) -> Result<()> {
    let root = root.unwrap_or_else(|| std::env::current_dir().unwrap());

    let parsed = mdpath::parse(&uri)
        .map_err(|e| anyhow::anyhow!("invalid md:// URI: {}", e))?;

    let element = mdpath::resolve(&parsed, &root)
        .map_err(|e| anyhow::anyhow!("resolve failed: {}", e))?;

    match format.as_str() {
        "json" => {
            let json = serde_json::json!({
                "uri": element.uri,
                "file": element.file.display().to_string(),
                "line_start": element.line_start,
                "line_end": element.line_end,
                "element_type": format!("{:?}", element.element_type),
                "kind": element.kind,
                "label": element.label,
                "section_heading": element.section_heading,
                "content": element.content,
            });
            println!("{}", serde_json::to_string_pretty(&json)?);
        }
        _ => {
            // text format
            println!("{}", element.uri.cyan());
            if let Some(h) = &element.section_heading {
                println!("  section:  {}", h);
            }
            if let Some(label) = &element.label {
                println!("  label:    {}", label);
            }
            if let Some(kind) = &element.kind {
                println!("  kind:     {}", kind);
            }
            println!("  lines:    {}–{}", element.line_start, element.line_end);
            println!("  file:     {}", element.file.display());
            println!();
            println!("{}", element.content);
        }
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// spec generate
// ─────────────────────────────────────────────────────────

fn cmd_spec_generate(
    uri: String,
    id_override: Option<String>,
    protection: String,
    root_override: Option<PathBuf>,
    output: Option<PathBuf>,
) -> Result<()> {
    let root = root_override.unwrap_or_else(|| std::env::current_dir().unwrap());

    // Resolve the URI
    let parsed = mdpath::parse(&uri)
        .map_err(|e| anyhow::anyhow!("invalid md:// URI {:?}: {}", uri, e))?;
    let element = mdpath::resolve(&parsed, &root)
        .map_err(|e| anyhow::anyhow!("cannot resolve {:?}: {}", uri, e))?;

    // Derive ID from URI if not provided
    let id = id_override.unwrap_or_else(|| {
        // Use the last path segment minus extension, falling back to "figure"
        parsed.path
            .split('/')
            .last()
            .unwrap_or("figure")
            .trim_end_matches(".md")
            .replace(['-', '_'], "-")
            .to_string()
    });

    eprintln!("{} Analyzing {} ({} lines)...",
        "→".cyan(),
        uri.dimmed(),
        element.content.lines().count(),
    );

    let spec = spec_gen::generate(
        &element.content,
        element.label.as_deref(),
        &uri,
        &id,
    );

    // Override protection from CLI
    let mut spec = spec;
    spec.protection = protection;

    let toml_out = spec_gen::format_toml(&spec);

    // Print summary to stderr, TOML to stdout (or file)
    eprintln!("{} {} invariant{} suggested for {:?}",
        "✓".green(),
        spec.invariants.len(),
        if spec.invariants.len() == 1 { "" } else { "s" },
        spec.id,
    );
    for inv in &spec.invariants {
        eprintln!("  {} [{}] {}",
            match inv.confidence {
                spec_gen::SuggestionConfidence::High   => "●".green().to_string(),
                spec_gen::SuggestionConfidence::Medium => "◐".yellow().to_string(),
                spec_gen::SuggestionConfidence::Low    => "○".dimmed().to_string(),
            },
            inv.confidence.label(),
            inv.rule,
        );
    }
    eprintln!();
    eprintln!("Paste the output below into your proof.toml, then run:");
    eprintln!("  proof check --daVinci .");
    eprintln!();

    match output {
        Some(path) => {
            std::fs::write(&path, &toml_out)?;
            eprintln!("{} written to {}", "✓".green(), path.display());
        }
        None => print!("{}", toml_out),
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// compile
// ─────────────────────────────────────────────────────────

fn cmd_compile(
    paths: Vec<PathBuf>,
    output_override: Option<PathBuf>,
    check_only: bool,
    root_override: Option<PathBuf>,
    config_override: &Option<PathBuf>,
) -> Result<()> {
    // Collect .source.md files
    let mut source_files: Vec<PathBuf> = Vec::new();
    for path in &paths {
        if path.is_file() {
            source_files.push(path.clone());
        } else {
            for entry in walkdir::WalkDir::new(path)
                .into_iter()
                .filter_map(|e| e.ok())
                .filter(|e| e.file_type().is_file())
            {
                let p = entry.path().to_path_buf();
                if p.to_str().map(|s| s.ends_with(".source.md")).unwrap_or(false) {
                    source_files.push(p);
                }
            }
        }
    }

    if source_files.is_empty() {
        eprintln!("{} no .source.md files found", "proof compile:".yellow());
        return Ok(());
    }

    if output_override.is_some() && source_files.len() > 1 {
        eprintln!("{} -o can only be used with a single source file", "error:".red());
        process::exit(2);
    }

    let root = root_override.unwrap_or_else(|| std::env::current_dir().unwrap());
    let config = load_config(&root, config_override);

    let mut total_errors = 0usize;
    let mut total_warnings = 0usize;
    let mut compiled = 0usize;

    for source_path in &source_files {
        let output_path = if let Some(ref out) = output_override {
            out.clone()
        } else if let Some(p) = derive_output_path(source_path) {
            p
        } else {
            eprintln!("{} {} has no .source.md suffix — use -o to specify output",
                "skip:".yellow(), source_path.display());
            continue;
        };

        if check_only {
            eprintln!("  {} {} → {} (check only)",
                "→".cyan(), source_path.display(), output_path.display());
        }

        let result = compile_file(source_path, &output_path, &root, &config)?;

        // Report violations
        for v in &result.violations {
            let sev = match v.severity {
                ViolationSeverity::Error   => { total_errors += 1; "error".red().bold().to_string() }
                ViolationSeverity::Warning => { total_warnings += 1; "warning".yellow().bold().to_string() }
            };
            eprintln!(
                "{}:{}:{}: {} [{}]: {}",
                source_path.display().to_string().cyan(),
                v.source_line, 1,
                sev, v.code, v.message
            );
            if let Some(ref id) = v.figure_id {
                eprintln!("    figure: {}", id);
            }
            if !v.uri.is_empty() {
                eprintln!("    uri:    {}", v.uri);
            }
        }

        if result.written {
            compiled += 1;
            eprintln!("{} {} → {}  ({} directive{})",
                "✓".green(),
                source_path.display().to_string().cyan(),
                output_path.display(),
                result.directives_resolved,
                if result.directives_resolved == 1 { "" } else { "s" },
            );
        } else if !result.violations.iter().any(|v| v.severity == ViolationSeverity::Error) {
            eprintln!("{} {} (no directives — pass-through)",
                "→".dimmed(), source_path.display());
            if !check_only {
                // Copy source to output unchanged
                std::fs::copy(source_path, &output_path)?;
                compiled += 1;
            }
        }
    }

    eprintln!();
    if total_errors > 0 {
        eprintln!("{} — {} compiled, {} error{}, {} warning{}",
            "FAIL".red().bold(), compiled,
            total_errors, if total_errors == 1 { "" } else { "s" },
            total_warnings, if total_warnings == 1 { "" } else { "s" },
        );
        process::exit(1);
    } else {
        eprintln!("{} — {} compiled, {} warning{}",
            "OK".green().bold(), compiled,
            total_warnings, if total_warnings == 1 { "" } else { "s" },
        );
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────
// layout
// ─────────────────────────────────────────────────────────

fn cmd_layout(
    sources: Vec<String>,
    gap: usize,
    align_str: String,
    labels: Vec<String>,
    cols: Option<usize>,
    width: usize,
    direction_str: String,
    border: bool,
    output: Option<PathBuf>,
    root: Option<PathBuf>,
) -> Result<()> {
    if sources.is_empty() {
        eprintln!("{} no sources provided — pass md:// URIs or file paths", "error:".red());
        process::exit(2);
    }

    let align = Align::parse(&align_str)?;
    let direction = Direction::parse(&direction_str)?;
    let root = root.unwrap_or_else(|| std::env::current_dir().unwrap());

    let config = LayoutConfig { gap, align, labels, cols, width, direction, border };

    // Resolve each source to content lines
    let mut figures: Vec<Vec<String>> = Vec::new();
    for source in &sources {
        let content = if source.starts_with("md://") {
            // Resolve via mdpath
            let parsed = mdpath::parse(source)
                .map_err(|e| anyhow::anyhow!("invalid md:// URI {:?}: {}", source, e))?;
            let element = mdpath::resolve(&parsed, &root)
                .map_err(|e| anyhow::anyhow!("cannot resolve {:?}: {}", source, e))?;
            element.content
        } else {
            // File path — read and use whole file content
            let path = root.join(source);
            std::fs::read_to_string(&path)
                .with_context(|| format!("reading figure file: {}", path.display()))?
        };
        figures.push(extract_content_lines(&content));
    }

    let result = layout::layout(figures, &config);

    match output {
        Some(path) => {
            std::fs::write(&path, &result)?;
            eprintln!("{} layout written to {}", "✓".green(), path.display());
        }
        None => println!("{}", result),
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────

fn cmd_draft(paths: Vec<PathBuf>, output: PathBuf, config_override: &Option<PathBuf>) -> Result<()> {
    // Collect all diagnostics (same as check)
    let mut all_diags: Vec<Diagnostic> = Vec::new();
    let root = paths.first().map(|p| if p.is_dir() { p.clone() } else { p.parent().unwrap_or(p).to_path_buf() })
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    for path in &paths {
        let cfg = load_config(path, config_override);
        let dir = if path.is_dir() { path.clone() } else { path.parent().unwrap_or(path).to_path_buf() };
        let runner = Runner::new(&dir, cfg)?;
        if path.is_file() {
            all_diags.extend(runner.lint_file(path));
        } else {
            all_diags.extend(runner.run());
        }
    }

    let error_count = all_diags.iter().filter(|d| d.severity == Severity::Error).count();
    let warn_count = all_diags.iter().filter(|d| d.severity == Severity::Warning).count();

    // Build the draft plan
    let draft = build_draft_plan(&all_diags, &root)?;

    let json = serde_json::to_string_pretty(&draft)?;
    std::fs::write(&output, &json)?;

    eprintln!(
        "{} — {} errors, {} warnings across {} groups ({} auto-fixable, {} need review)",
        "draft".cyan().bold(),
        error_count, warn_count,
        draft.summary.total_groups,
        draft.summary.auto_fixable,
        draft.summary.needs_review,
    );
    eprintln!("Draft plan written to {}", output.display().to_string().cyan());
    eprintln!();
    eprintln!("Next steps:");
    eprintln!("  1. Open {} — AI fills in `decision` and `new_string` for non-auto groups", output.display());
    eprintln!("  2. proof fix --plan {} --dry-run", output.display());
    eprintln!("  3. proof fix --plan {}", output.display());

    Ok(())
}

/// Load a plan file — accepts both FixPlan and DraftPlan formats.
/// DraftPlan is automatically converted to FixPlan via to_fix_plan().
fn load_plan(path: &std::path::Path) -> anyhow::Result<FixPlan> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("reading plan file: {}", path.display()))?;

    // Try FixPlan first (has "schema_version" + "fixes" array)
    if let Ok(plan) = serde_json::from_str::<FixPlan>(&content) {
        return Ok(plan);
    }

    // Try DraftPlan (has "schema_version" + "groups" array)
    if let Ok(draft) = serde_json::from_str::<proof_lib::draft::DraftPlan>(&content) {
        eprintln!("{} converting draft plan to fix plan (auto+annotated groups only)",
            "info:".cyan());
        return Ok(draft.to_fix_plan());
    }

    anyhow::bail!("cannot parse {} as FixPlan or DraftPlan", path.display())
}

fn load_config(path: &std::path::Path, override_path: &Option<PathBuf>) -> GlintConfig {
    if let Some(ref cfg_path) = override_path {
        match GlintConfig::load(cfg_path) {
            Ok(cfg) => return cfg,
            Err(e) => eprintln!("proof: warning: {}", e),
        }
    }
    let dir = if path.is_dir() { path.to_path_buf() } else { path.parent().unwrap_or(path).to_path_buf() };
    GlintConfig::load_or_default(&dir)
}

fn cmd_init() -> Result<()> {
    let path = std::path::Path::new("proof.toml");
    if path.exists() {
        eprintln!("{} proof.toml already exists", "warning:".yellow());
        return Ok(());
    }
    let content = include_str!("../schemas/default.toml");
    std::fs::write(path, content)?;
    println!("{} proof.toml created", "OK".green().bold());
    Ok(())
}

fn count_files(dir: &std::path::Path) -> usize {
    walkdir::WalkDir::new(dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.file_type().is_file()
                && e.path().extension().map(|x| x == "md").unwrap_or(false)
        })
        .count()
}
